spring:

    datasource:
      url : "jdbc:mysql://localhost:3306/football_database"
      username: root
      password: root
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
server:
  port: 8888

